# Generated by Django 5.1.1 on 2024-09-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0005_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='images',
            new_name='HomepageImage',
        ),
    ]
