# Generated by Django 3.2.25 on 2024-10-28 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0019_delete_profile_rename_image_homepageimage_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('subheading', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_images/')),
            ],
        ),
    ]
