# Generated by Django 5.1.6 on 2025-02-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0023_auto_20241029_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
