# Generated by Django 5.1.1 on 2024-09-30 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0004_product_remove_cart_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='home_images')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
