# Generated by Django 5.1.1 on 2024-10-04 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0008_homepageimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomepageImage',
        ),
    ]
