# Generated by Django 5.1.1 on 2024-10-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0009_delete_homepageimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/%x'),
        ),
    ]
