# Generated by Django 5.1.1 on 2024-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0015_produce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='image_url',
            field=models.URLField(max_length=1200),
        ),
    ]
