# Generated by Django 5.1.2 on 2024-10-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joseph', '0018_alter_book_cover_image_alter_book_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RenameField(
            model_name='homepageimage',
            old_name='image',
            new_name='profile',
        ),
    ]
